/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form; 

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author hector_duarte
 */
public class form extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(form.class.getName());

    /**
     * Creates new form form
     */
    public form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_lastname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_second_lastname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_phone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_age = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        btn_create = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_read = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_datos = new javax.swing.JTable();
        btn_update = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Students");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 20, 60, 30);

        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 70, 50, 30);
        getContentPane().add(tf_name);
        tf_name.setBounds(160, 70, 300, 30);

        jLabel3.setText("Lastname");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(110, 110, 70, 30);
        getContentPane().add(tf_lastname);
        tf_lastname.setBounds(180, 110, 280, 30);

        jLabel4.setText("Second lastname");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 150, 110, 30);
        getContentPane().add(tf_second_lastname);
        tf_second_lastname.setBounds(220, 150, 240, 30);

        jLabel5.setText("Phone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(110, 190, 50, 30);
        getContentPane().add(tf_phone);
        tf_phone.setBounds(160, 190, 300, 30);

        jLabel6.setText("Age");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(110, 230, 50, 30);
        getContentPane().add(tf_age);
        tf_age.setBounds(160, 230, 300, 30);

        jLabel7.setText("ID");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 20, 30, 30);

        tf_id.setEnabled(false);
        getContentPane().add(tf_id);
        tf_id.setBounds(400, 20, 60, 30);

        btn_create.setText("Create");
        btn_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                create(evt);
            }
        });
        getContentPane().add(btn_create);
        btn_create.setBounds(100, 290, 72, 23);

        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete(evt);
            }
        });
        getContentPane().add(btn_delete);
        btn_delete.setBounds(190, 290, 72, 23);

        btn_read.setText("Read");
        btn_read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                read(evt);
            }
        });
        getContentPane().add(btn_read);
        btn_read.setBounds(280, 290, 72, 23);

        tbl_datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Lastname", "Second Lastname", "Phone", "Age"
            }
        ));
        tbl_datos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                get_data(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_datos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 330, 540, 300);

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update(evt);
            }
        });
        getContentPane().add(btn_update);
        btn_update.setBounds(370, 290, 73, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clean(){
        tf_id.setText("");
        tf_name.setText("");
        tf_lastname.setText("");
        tf_second_lastname.setText("");
        tf_phone.setText("");
        tf_age.setText("");
    }
    
    private void table_update(){
        List<Map<String, Object>> datos = bd.leer(configuracion, tabla);
        DefaultTableModel model = (DefaultTableModel) tbl_datos.getModel();
        model.setRowCount(0);
        for (Map<String, Object> fila : datos) {
            model.addRow(new Object[]{
                fila.get("id"),
                fila.get("name"),
                fila.get("lastname"),
                fila.get("second_lastname"),
                fila.get("phone"),
                fila.get("edad")
            });
        }
    }
    
    private void create(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_create
        // TODO add your handling code here:
        Map datos = new HashMap();
        datos.put(campos[0], tf_name.getText());
        datos.put(campos[1], tf_lastname.getText());
        datos.put(campos[2], tf_second_lastname.getText());
        datos.put(campos[3], tf_phone.getText());
        datos.put(campos[4], tf_age.getText());
        bd.crear(datos, configuracion, tabla);
        clean();
        table_update();
    }//GEN-LAST:event_create

    private void delete(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete
        // TODO add your handling code here:
        int id = Integer.parseInt(tf_id.getText());
        bd.borrar(id, configuracion, tabla);
        clean();
        table_update();
    }//GEN-LAST:event_delete

    private void read(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_read
        // TODO add your handling code here:
        table_update();
    }//GEN-LAST:event_read

    private void get_data(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_get_data
        // TODO add your handling code here:
        int fila = tbl_datos.getSelectedRow();
        if(fila >= 0){
            tf_id.setText(tbl_datos.getValueAt(fila, 0).toString());
            tf_name.setText(tbl_datos.getValueAt(fila,1).toString());
            tf_lastname.setText(tbl_datos.getValueAt(fila,2).toString());
            tf_second_lastname.setText(tbl_datos.getValueAt(fila,3).toString());
            tf_phone.setText(tbl_datos.getValueAt(fila, 4).toString());
            tf_age.setText(tbl_datos.getValueAt(fila, 5).toString());        
        }
    }//GEN-LAST:event_get_data

    private void update(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update
        // TODO add your handling code here:
        int id = Integer.parseInt(tf_id.getText());
        Map datos = new HashMap();
        datos.put(campos[0],tf_name.getText());
        datos.put(campos[1],tf_lastname.getText());
        datos.put(campos[2],tf_second_lastname.getText());
        datos.put(campos[3],tf_phone.getText());
        datos.put(campos[4],tf_age.getText());
        
        bd.actualizar(id, datos, configuracion, tabla);
        clean();
        table_update();
    }//GEN-LAST:event_update

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_create;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_read;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tbl_datos;
    private javax.swing.JTextField tf_age;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_lastname;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phone;
    private javax.swing.JTextField tf_second_lastname;
    // End of variables declaration//GEN-END:variables
    String [] configuracion = {"localhost","root","JHtest13","register"};
    String tabla = "Students";
    String [] campos = {"name","lastname","second_lastname","phone","edad"};
    MySQLGenerico bd = new MySQLGenerico();
}
